//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appartment
    {
        public int AppartmentId { get; set; }
        public int BuildingId { get; set; }
        public bool Available { get; set; }
        public int NumOfBedrooms { get; set; }
        public int NumOfBathRooms { get; set; }
        public string Size { get; set; }
        public int Price { get; set; }
    
        public virtual Building Building { get; set; }
    }
}
