//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Building
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Building()
        {
            this.Appartments = new HashSet<Appartment>();
        }
        public string FullAddress { get { return Address+" "+City+" "+Province+" "+PostalCode; } }
        public int BuildingId { get; set; }
        public int PropertyOwnerId { get; set; }
        public int PropertyManagerId { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string PostalCode { get; set; }
        public string BuildingName { get; set; }
        public bool HasLaundry { get; set; }
        public bool HasParking { get; set; }
        public bool IncludeUtils { get; set; }
        public bool CloseToTransit { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appartment> Appartments { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
